In [3]:
#McCulloh Pitt model for AND model
import numpy as np

def McAnd(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output

x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([1,1,-1])

t = 0
ans1 = McAnd(x0,w,t)
print (x0, "value", ans1)
ans2 = McAnd(x1,w,t)
print (x1, "value", ans2)
ans3 = McAnd(x2,w,t)
print (x2, "value", ans3)
ans4 = McAnd(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value 0
[0 1 1] value 0
[1 0 1] value 0
[1 1 1] value 1


In [4]:
import numpy as np
def McOR(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output

x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([5,5,-4])

t = 0
ans1 = McOR(x0,w,t)
print (x0, "value", ans1)
ans2 = McOR(x1,w,t)
print (x1, "value", ans2)
ans3 = McOR(x2,w,t)
print (x2, "value", ans3)
ans4 = McOR(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value 0
[0 1 1] value 1
[1 0 1] value 1
[1 1 1] value 1


In [5]:
def NOT(x):

result=[1,0]

input1=[0,1]


for i in range(-6,-1):

sol=[]

for k in range(2):

y=i*input1[k]

if(y>n or y==n):

sol.append(1)

else:

sol.append(0)

if(sol==result):

return(i)

IndentationError: expected an indented block (1229870016.py, line 3)

In [7]:

def NOT(x):

result=[1,0]

input1=[0,1]


for i in range(-6,-1):

sol=[]

for k in range(2):

y=i*input1[k]

if(y>n or y==n):

sol.append(1)

else:

sol.append(0)

if(sol==result):

return(i)

IndentationError: expected an indented block (3678353712.py, line 3)

In [8]:
def McNOT(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output

x0 = np.array([0,1])
x1 = np.array([1,1])

w = np.array([-1,1])

t = 0
ans1 = McNOT(x0,w,t)
print (x0, "value", ans1)
ans2 = McNOT(x1,w,t)
print (x1, "value", ans2)


[0 1] value 1
[1 1] value 0
